Use Ecommerce;

INSERT INTO Customers(Name,Email,Address)
VALUES
('Aamir','Aamir@Whatmobile.Com.Pk','
Mumbai'),
('Aamir','aamir.rais150@gmail.com','
Delhi'),
('Abbas','Abbas_raza94@Hotmail.Com','
Chennai'),
('Abdul','Kamranwahid2032@Ymail.Com','
Kolkata'),
('Abdul','ubaidaslam1988@gmail.com','
Chennai'),
('Abdul','Abdulmoizmohsin@Gmail.Com','
Bangalore'),
('Dua','DuaAbbas@gmail.com','
Chennai'),
('Duncan','DuncanMajeed@gmail.com','
Mumbai'),
('Ehtsham','EhtshamRaheem@gmail.com','
Delhi'),
('Ejaz','EjazHaq@gmail.com','
Bangalore'),
('Faaz','FaazRehman@gmail.com','
Hyderabad'),
('Fahad','FahadSamad@gmail.com','
Kolkata'),
('fahd','fahdAziz@gmail.com','
Hyderabad'),
('Faheem','FaheemWaqar@gmail.com','
Bangalore'),
('Faisal','FaisalRAZZIQUE@gmail.com','
Mumbai'),
('Faisal','FaisalKardar@gmail.com','
Delhi'),
('Faisal','FaisalMemon@gmail.com','
Bangalore'),
('Faran','FaranKhan@gmail.com','
Kolkata'),
('Farhan','FarhanAbbasi@gmail.com','
Bangalore'),
('Hammad','HammadHussain@gmail.com','
Kolkata'),
('Hamza','HamzaAsghar@gmail.com','
Chennai'),
('Hamza','HamzaMehmood@gmail.com','
Mumbai'),
('HAMZA','HAMZADaniyal@gmail.com','
Chennai'),
('Hamza','HamzaMuhammad@gmail.com','
Kolkata'),
('hamza','hamzaShadab@gmail.com','
Delhi'),
('Hamza','Ishaque','HamzaIshaque@gmail.com','
Chennai'),
('Hamza','HamzaFang@gmail.com','
Kolkata'),
('Hamza','HamzaAnjum@gmail.com','
Mumbai'),
('Haroon','Ahmed','HaroonAhmed@gmail.com','
Mumbai'),
('Haroon','Ali','HaroonAli@gmail.com','
Kolkata'),
('Hasan','Babar','HasanBabar@gmail.com','
Chennai'),
('Haseeb','Abbas','HaseebAbbas@gmail.com','
Bangalore'),
 
